FROM ruby:3.2.2

RUN apt-get update && apt-get install -y

ENV HOME=/usr/src/app
WORKDIR $HOME

ENV BUNDLER_VERSION=2.4.19
RUN gem update --system
RUN gem install bundler:$BUNDLER_VERSION

ADD Gemfile $HOME/Gemfile
ADD Gemfile.lock $HOME/Gemfile.lock

RUN bundle install

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["sh", "/docker-entrypoint.sh"]

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
