version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - .:/usr/src/app
      - bundle_data:/bundle
    env_file:
      - .env.development
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.development

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app
      - bundle_data:/bundle

  redis:
    image: redis:7.2.0
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
  bundle_data:
  redis_data: